name: Publish

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  packages: read
  pull-requests: write

env:
  GITHUB_USER: vshpyrka
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    name: Publish
    runs-on: ubuntu-latest
    env:
      GITHUB_PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      GITHUB_ACTOR: ${{ secrets.ACTOR }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-build-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Extract existing versions
        id: extract_versions
        run: |
          # Get existing version code from build.gradle
          version_code=$(grep "versionCode" app/build.gradle.kts | awk -F'= ' '{print $2}')
          version_name=$(grep "versionName" app/build.gradle.kts | awk -F'= ' '{print $2}')
          echo "current_version_code=$version_code" >> $GITHUB_OUTPUT
          echo "current_version_name=$version_name" >> $GITHUB_OUTPUT

      - name: Increase version code and change version name
        id: increase_version
        run: |
            # Update build.gradle with new version code and name
            current_version_code="${{ steps.extract_versions.outputs.current_version_code }}"
            current_version_name="${{ steps.extract_versions.outputs.current_version_name }}"
            
            # Increment existing version code by 1
            final_version_code=$((current_version_code + 1))
            version_number=$(echo "$current_version_name" | sed 's/v//')
            IFS='.' read -ra version_parts <<< "$version_number"
            version_parts[-1]=$((version_parts[-1]+1))
            final_version_name="${version_parts[0]}.${version_parts[1]}"
            
            # Update build.gradle with new version code and name
            echo "$final_version_code - $final_version_name"
            
            # Use sed to replace the values.
            # The regex tries to match "versionCode = ANY_NUMBER" and "versionName = "ANY_STRING""
            # -i means edit in place
            sed -i "s/versionCode = .*/versionCode = $final_version_code/" app/build.gradle.kts
            sed -i "s/versionName = .*/versionName = \"$final_version_name\"/" app/build.gradle.kts
            # Note the escaped quotes for versionName if it's a string
          
            grep "versionCode =" app/build.gradle.kts 
            grep "versionName =" app/build.gradle.kts
          
            echo "final_version_code=$final_version_code" >> $GITHUB_OUTPUT
            echo "final_version_name=$final_version_name" >> $GITHUB_OUTPUT

      - name: Push new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Push new version to a new branch
          version_code="${{ steps.increase_version.outputs.final_version_code }}"
          version_name="${{ steps.increase_version.outputs.final_version_name }}"
          branch="release/$version_name"
          git config user.name "Victor Shpyrka"
          git config user.email "victor.shpyrka@gmail.com"
          git checkout -b ${branch}
          git add app/build.gradle.kts
          git commit -m "chore: bump version to $version_name"
          git push origin ${branch}
          
          # Create a pull request
          sleep 5  # wait 5s for the branch to be pushed (sometimes information about the pushed branch is not available immediately)
          pr_url=$(gh pr create \
            --title "chore: bump version to $version_name" \
            --body "Bump version to $version_name" \
            --base master \
            --head "release/$version_name"
          )
          echo "pr_url=${pr_url}" >> $GITHUB_OUTPUT
          
          # github.token is used because approval cannot be granted by the author of the PR
          GH_TOKEN=${{ github.token }} 
          gh pr review "${pr_url}" --approve
          
          # attempt to merge, but don't fail if it doesn't work
          gh pr merge "${pr_url}" --auto --merge || echo "PR can't be merged automatically"

#      - name: Build Release
#        run: ./gradlew :app:bundleRelease --parallel
#
#      - name: Sign Android release
#        uses: r0adkll/sign-android-release@v1
#        with:
#          releaseDirectory: app/build/outputs/bundle/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}
#
#      - name: Deploy to Internal Alpha
#        uses: r0adkll/upload-google-play@v1.1.3
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_TEXT }}
#          packageName: com.vshpyrka.playground
#          releaseFiles: app/build/outputs/bundle/release/app-release.aab
#          track: internal alpha
#          changesNotSentForReview: true